name: Deploy application Docker Image to Azure VM

on:
  push:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Dockerhub
        id: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Tag, and Push image to dockerhub
        id: build-image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG  
          echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT   

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stop and remove all Docker containers and images
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -aq | xargs -r docker rm
          docker images -q | xargs -r docker rmi -f

      - name: Run Docker Image
        run: |
          docker run -d \
          -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_REGION_NAME="${{ secrets.AWS_REGION_NAME }}" \
          -e BUCKET_NAME="${{ secrets.BUCKET_NAME }}" \
          -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
          -p 5000:5000 "${{ secrets.DOCKER_REGISTRY }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest